AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - node_modules/**/*
    - spec/*.rb
  TargetRubyVersion: 2.6
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
