version: 2
jobs:
  test:
    docker:
      - image: artsy/hokusai:0.4.6
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: hokusai test
  deploy:
    docker:
      - image: artsy/hokusai:0.4.6
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
      - run: hokusai staging deploy $CIRCLE_SHA1
      - run: git push git@github.com:artsy/reflection.git $CIRCLE_SHA1:refs/heads/staging --force
  promote:
    docker:
      - image: artsy/hokusai:0.4.6
    steps:
      - add_ssh_keys
      - checkout
      - run: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run: hokusai pipeline promote
workflows:
  version: 2
  default:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - staging
                - release
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test
      - promote:
          filters:
            branches:
              only: release
