version: 2.1

orbs:
  hokusai: artsy/hokusai@0.7.5
  horizon: artsy/release@0.0.1
  artsy-remote-docker: artsy/remote-docker@0.1.5

jobs:
  test:
    executor: hokusai/deploy
    steps:
      - hokusai/setup-docker
      - run: hokusai registry pull --tag "$CIRCLE_SHA1"
      - hokusai/run-tests

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  build-deploy:
    jobs:
      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 38

      - artsy-remote-docker/build:
          <<: *not_staging_or_release
          context: hokusai
          name: build

      - test:
          <<: *not_staging_or_release
          context: hokusai
          requires:
            - build

      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - test

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: horizon
          requires:
            - push-staging-image

      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
