version: 2
jobs:
  test:
    docker:
      - image: artsy/hokusai:0.5.0
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: hokusai test
  deploy:
    docker:
      - image: artsy/hokusai:0.5.0
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
      - run: hokusai staging deploy $CIRCLE_SHA1
      - run: git push git@github.com:artsy/horizon.git $CIRCLE_SHA1:refs/heads/staging --force
workflows:
  version: 2
  default:
    jobs:
      - test:
          filters:
            branches:
              ignore: staging
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test
