version: 2.1

orbs:
  hokusai: artsy/hokusai@0.7.0

not_staging: &not_staging
  filters:
    branches:
      ignore:
        - staging

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

workflows:
  build-deploy:
    jobs:
      - hokusai/test:
          <<: *not_staging

      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - hokusai/test

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: horizon
          requires:
            - push-staging-image
