---
version: "3.8"
services:
  horizon:
    image: "hokusai_horizon:${BUILD_TAG:-latest}"
    build:
      target: "${BUILD_TARGET}"
{% include 'templates/docker-compose-build.j2' %}
    environment:
{% include 'templates/docker-compose-environment.j2' %}