---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horizon-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horizon
        component: web
        layer: application
      name: horizon-web
    spec:
      containers:
      - name: horizon-web
        env:
        - name: RAILS_ENV
          value: production
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: horizon-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/horizon:production
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 8080
        - containerPort: 8443
        resources:
          requests:
            cpu: 200m
            memory: 800Mi
          limits:
            memory: 1Gi
        readinessProbe:
          httpGet:
            port: 8080
            path: /robots.txt
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: horizon
    component: web
    layer: application
  name: horizon-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 8443
  - port: 80
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: horizon
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: horizon-refresh-cron
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: horizon-refresh-cron
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/horizon:production
            args: ["bundle", "exec", "rake", "cron:refresh_comparisons"]
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: horizon-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
