---
version: '2'
services:
  horizon:
    command: ./hokusai/ci.sh
    depends_on:
    - horizon-postgres
    environment:
    - DATABASE_URL=postgresql://postgres:@horizon-postgres/horizon_test
    - RAILS_ENV=test
    extends:
      file: build.yml
      service: horizon
  horizon-postgres:
    image: postgres:9.5
