---
version: '2'
services:
  horizon:
    command: bundle exec rake db:setup spec
    depends_on:
    - horizon-postgres
    - horizon-redis
    environment:
    - DATABASE_URL=postgresql://postgres:@horizon-postgres/horizon_test
    - RAILS_ENV=test
    - REDIS_URL=redis://horizon-redis
    extends:
      file: build.yml
      service: horizon
    volumes:
    - ../:/app
  horizon-postgres:
    image: postgres:9.5
  horizon-redis:
    image: redis:3.2-alpine
